[build]
	publish = "dist" 

[[redirects]]
  from = "/*"
  to = "https://vue3-vuex-spa-app.netlify.app/"
  status = 301
  # force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}